**Intro to Julia**

In [14]:
1+1

2

In [15]:
println("Hello,World!")

Hello,World!


In [16]:
n = 123

123

In [17]:
typeof(n)

Int64

In [18]:
π₁= 3.1316

3.1316

In [19]:
typeof(π₁)

Float64

In [22]:
🍎 ="apple"
println(🍎)

apple


In [23]:
typeof(🍎)

String

In [24]:
typeof(1==1)

Bool

In [25]:
100/10

10.0

In [26]:
typeof(100//10)

Rational{Int64}

In [29]:
100%13

9

In [30]:
typeof(convert(Int32,100))

Int32

In [31]:
typeof(convert(Int16,100))

Int16

In [34]:
# ?convert find information

In [36]:
# @doc println find information

In [37]:
#= multiple lines for comments
......
......
......
=#

In [41]:
# convert(Int64,"1234") failed 

In [42]:
parse(Int64,"1234")

1234

#### String

In [43]:
s = "this is a string"

"this is a string"

In [44]:
println(s)

this is a string


In [47]:
"""
this is a string 
this is another string
"""

"this is a string \nthis is another string\n"

In [48]:
typeof('a')

Char

In [50]:
c = 3.14

3.14

In [52]:
"pi = $c" # in python: f"{c}"

"pi = 3.14"

In [53]:
"two_c = $(c*2)"

"two_c = 6.28"

In [54]:
"$(100*3)"

"300"

In [55]:
"abc"*"def"

"abcdef"

In [56]:
"abc"*"abc"*"abc"

"abcabcabc"

In [57]:
"abc"^3

"abcabcabc"

In [59]:
string("abc","def")

"abcdef"

#### Tuple

In [61]:
("a","b")

("a", "b")

In [62]:
(1,2,3,4,5,6)

(1, 2, 3, 4, 5, 6)

In [63]:
typeof(("a","b"))

Tuple{String, String}

In [64]:
typeof(("a",1))

Tuple{String, Int64}

In [66]:
fruits = ("🍎","🍌","🍐")

("🍎", "🍌", "🍐")

In [67]:
typeof(fruits)

Tuple{String, String, String}

In [68]:
fruits[1]

"🍎"

In [69]:
fruits[2]

"🍌"

In [70]:
fruits[3]

"🍐"

 ##### named tuples

In [71]:
ordered_fruits = (first = "🍎",second = "🍌",third = "🍐")

(first = "🍎", second = "🍌", third = "🍐")

In [72]:
ordered_fruits.first

"🍎"

In [73]:
ordered_fruits.second

"🍌"

In [75]:
ordered_fruits[1]

"🍎"

#### Disctionaries

In [80]:
dict_fruits = Dict("first" => "🍎","second" => "🍌","third" => "🍐")

Dict{String, String} with 3 entries:
  "second" => "🍌"
  "first"  => "🍎"
  "third"  => "🍐"

In [81]:
dict_fruits["first"]

"🍎"

In [84]:
dict_fruits["first"] = "🍉"

"🍉"

In [85]:
dict_fruits

Dict{String, String} with 3 entries:
  "second" => "🍌"
  "first"  => "🍉"
  "third"  => "🍐"

In [86]:
dict_fruits["best"] = "🍎"

"🍎"

In [87]:
dict_fruits

Dict{String, String} with 4 entries:
  "second" => "🍌"
  "first"  => "🍉"
  "third"  => "🍐"
  "best"   => "🍎"

In [88]:
pop!(dict_fruits,"best")

"🍎"

In [89]:
dict_fruits

Dict{String, String} with 3 entries:
  "second" => "🍌"
  "first"  => "🍉"
  "third"  => "🍐"

#### Arrays

In [94]:
["🍎","🍌","🍐"]

3-element Vector{String}:
 "🍎"
 "🍌"
 "🍐"

In [95]:
array_fruits = ["🍎","🍌","🍐"]

3-element Vector{String}:
 "🍎"
 "🍌"
 "🍐"

In [97]:
fib = [1,1,2,3,4,5,6]

7-element Vector{Int64}:
 1
 1
 2
 3
 4
 5
 6

In [101]:
fib[3]

2

In [98]:
[1,1.0]

2-element Vector{Float64}:
 1.0
 1.0

In [99]:
[1,1.0,"a"]

3-element Vector{Any}:
 1
 1.0
  "a"

In [107]:
array_fruits1 = ["🍎","🍌","🍐"]

3-element Vector{String}:
 "🍎"
 "🍌"
 "🍐"

In [108]:
array_fruits1[2]

"🍌"

In [109]:
array_fruits1[2] = "banana"

"banana"

In [110]:
array_fruits1

3-element Vector{String}:
 "🍎"
 "banana"
 "🍐"

In [111]:
push!(fib,12345)

8-element Vector{Int64}:
     1
     1
     2
     3
     4
     5
     6
 12345

In [112]:
pop!(fib)

12345

In [113]:
[[1,2,3],[4,5,6]]

2-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5, 6]

In [114]:
[[1,2,3],[4,5,6,7]]

2-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5, 6, 7]

In [115]:
rand(4,3)

4×3 Matrix{Float64}:
 0.48247     0.496644  0.719476
 0.00937945  0.880942  0.992877
 0.707789    0.565142  0.353787
 0.0821327   0.831566  0.777347

In [116]:
rand(2,3,4,5,6)

2×3×4×5×6 Array{Float64, 5}:
[:, :, 1, 1, 1] =
 0.0567787  0.93681   0.643495
 0.87758    0.879858  0.837055

[:, :, 2, 1, 1] =
 0.0641527  0.67364   0.456803
 0.742403   0.622489  0.57587

[:, :, 3, 1, 1] =
 0.218711  0.0496468  0.349736
 0.434453  0.138925   0.958326

[:, :, 4, 1, 1] =
 0.768628  0.780388   0.737307
 0.176362  0.0678671  0.960816

[:, :, 1, 2, 1] =
 0.83395   0.18981   0.528336
 0.526413  0.430758  0.769878

[:, :, 2, 2, 1] =
 0.580636  0.383829  0.659033
 0.642938  0.783438  0.607517

[:, :, 3, 2, 1] =
 0.0649676  0.607514  0.616262
 0.528775   0.908164  0.194505

[:, :, 4, 2, 1] =
 0.500769  0.89004   0.615101
 0.233737  0.123916  0.245151

[:, :, 1, 3, 1] =
 0.45251   0.136071  0.0424627
 0.940116  0.869553  0.737694

[:, :, 2, 3, 1] =
 0.796588  0.545811  0.629728
 0.601568  0.152073  0.561488

[:, :, 3, 3, 1] =
 0.781614  0.284421  0.0370718
 0.899276  0.779488  0.927877

[:, :, 4, 3, 1] =
 0.352356  0.151537  0.808293
 0.485586  0.859386  0.0233992

[:, :, 1, 4

In [117]:
array_fruits = ["🍎","🍌","🍐"]

3-element Vector{String}:
 "🍎"
 "🍌"
 "🍐"

In [118]:
array_fruits2 = copy(array_fruits)

3-element Vector{String}:
 "🍎"
 "🍌"
 "🍐"

In [119]:
array_fruits2[2] = "banana"

"banana"

In [120]:
array_fruits2

3-element Vector{String}:
 "🍎"
 "banana"
 "🍐"

#### Loop

##### While Loop

In [125]:
n = 1
while n <= 10
    println(n)
    n+=1
end

1
2
3
4
5
6
7
8
9
10


In [126]:
n = 1
while n <= 10
    print(n)
    n+=1
end

12345678910

In [127]:
n = 1
s = 0 
while n <= 10
    s += n
    println("$n:$s")
    n+=1
end

1:1
2:3
3:6
4:10
5:15
6:21
7:28
8:36
9:45
10:55


In [129]:
fib = [1,1,2,3,5,8]
i = 1
while i<=length(fib)
    println(fib[i])
    i+=1
end

1
1
2
3
5
8


In [132]:
i = length(fib)+1
while i <= 30
    push!(fib,fib[i-1]+fib[i-2])
    i+=1
end
fib

30-element Vector{Int64}:
      1
      1
      2
      3
      5
      8
     13
     21
     34
     55
     89
    144
    233
      ⋮
   4181
   6765
  10946
  17711
  28657
  46368
  75025
 121393
 196418
 317811
 514229
 832040

In [133]:
fib = [1,1,2,3,5,8]
while fib[end] <= 10000
    push!(fib,fib[end]+fib[end-1])
end
fib

21-element Vector{Int64}:
     1
     1
     2
     3
     5
     8
    13
    21
    34
    55
    89
   144
   233
   377
   610
   987
  1597
  2584
  4181
  6765
 10946

##### For Loop

In [134]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [138]:
for n in 1:2:20
    println(n)
end

1
3
5
7
9
11
13
15
17
19


In [139]:
for n in 20:-1:1
    println(n)
end

20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1


In [135]:
fib

21-element Vector{Int64}:
     1
     1
     2
     3
     5
     8
    13
    21
    34
    55
    89
   144
   233
   377
   610
   987
  1597
  2584
  4181
  6765
 10946

In [136]:
for n in fib
    println("$n")
end

1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946


In [141]:
m,n = 5,5
A = fill(0,(m,n))

5×5 Matrix{Int64}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [142]:
for j in 1:n
    for i in 1:m
        A[i,j] = i+j
    end
end
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [144]:
m,n = 5,5
A = fill(0,(m,n))
for j in 1:n,i in 1:m
    A[i,j] = i+j
end
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [145]:
[i+j for i in 1:m,j in 1:n]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

#### Conditionals

In [151]:
for i in 1:10
    print(i)
    if i%3 ==0
        println("~0")
    elseif i%3 ==1
        println("~1")
    else 
        println("~2")
    end
end

1~1
2~2
3~0
4~1
5~2
6~0
7~1
8~2
9~0
10~1


In [162]:
i = 10

10

In [163]:
    if i%3 ==0
        "~0"
    elseif i%3 ==1
        "~1"
    else 
        "~2"
    end

"~1"

In [164]:
if i%3 ==0 "~0" elseif i%3 ==1 "~1" else "~2"end

"~1"

In [165]:
1==1&&2==2

true

In [166]:
1==1 || 2==2

true

In [171]:
for a in [false, true], b in [false,true]
    println("a:$a, b:$b, a&&b:$(a&&b)")
end

a:false, b:false, a&&b:false
a:false, b:true, a&&b:false
a:true, b:false, a&&b:false
a:true, b:true, a&&b:true


In [172]:
for a in [false, true], b in [false,true]
    println("a:$a, b:$b, a or b:$(a||b)")
end

a:false, b:false, a or b:false
a:false, b:true, a or b:true
a:true, b:false, a or b:true
a:true, b:true, a or b:true


In [174]:
true && "abcdefg"

"abcdefg"

In [179]:
true && print("abcdefg")

abcdefg

In [183]:
true && (for i in 1:10 print(i) end)

12345678910

In [184]:
true && (for i in 1:10 println(i) end)

1
2
3
4
5
6
7
8
9
10


In [180]:
true ? "a" : "b"

"a"

In [181]:
(5>3) ? "a" : "b"

"a"

#### Function

In [204]:
function hello(name)
    println("Hello, $name")
end

hello (generic function with 1 method)

In [205]:
hello("Lzc")

Hello, Lzc


In [189]:
hello(1234)

Hello, 1234


In [191]:
hello((a=1,b=2))

Hello, (a = 1, b = 2)


In [192]:
function f(x)
    x^2
end

f (generic function with 1 method)

In [193]:
f(2.0) 

4.0

In [199]:
f2(x)=x^2
hello2(name)= println("hello $name")
f2("aa")

"aaaa"

In [200]:
hello2("lzc")

hello lzc


In [201]:
f2(11)

121

In [202]:
hello3 = name -> println("Hello $name")

#3 (generic function with 1 method)

In [203]:
hello3("lzc")

Hello lzc


##### Duck-typing

In [207]:
f2("lzc")

"lzclzc"

In [208]:
f3(x) = x*2
f3(100)

200

In [209]:
f3("aaa")

LoadError: MethodError: no method matching *(::String, ::Int64)
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:591
  *(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:88
  *(::Union{AbstractChar, AbstractString}, ::Union{AbstractChar, AbstractString}...) at strings/basic.jl:260
  ...

In [211]:
v = rand(3)

3-element Vector{Float64}:
 0.13849601428566394
 0.24425863976938678
 0.8743862433446508

In [213]:
f3(v)

3-element Vector{Float64}:
 0.2769920285713279
 0.48851727953877355
 1.7487724866893015

In [215]:
# @doc f3(v)

##### Mutating

In [221]:
v = [3,7,6,5,2]

5-element Vector{Int64}:
 3
 7
 6
 5
 2

In [222]:
sort(v)

5-element Vector{Int64}:
 2
 3
 5
 6
 7

In [223]:
v

5-element Vector{Int64}:
 3
 7
 6
 5
 2

In [226]:
sort!(v) # will save 

5-element Vector{Int64}:
 2
 3
 5
 6
 7

In [227]:
v

5-element Vector{Int64}:
 2
 3
 5
 6
 7

##### Higher Order Function 

In [229]:
map(f,[1,2,3,4])

4-element Vector{Int64}:
  1
  4
  9
 16

In [231]:
map(x -> x%3,1:10)

10-element Vector{Int64}:
 1
 2
 0
 1
 2
 0
 1
 2
 0
 1

In [232]:
 map(x -> x^2,1:10)

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [233]:
broadcast(f,[1,2,3])

3-element Vector{Int64}:
 1
 4
 9

In [234]:
f.([1,3,4])

3-element Vector{Int64}:
  1
  9
 16

In [238]:
A = [i*2+3*j for j in 0:2, i in 0:2]

3×3 Matrix{Int64}:
 0  2   4
 3  5   7
 6  8  10

In [239]:
A^2

3×3 Matrix{Int64}:
 30   42   54
 57   87  117
 84  132  180

In [241]:
A^3

3×3 Matrix{Int64}:
  450   702   954
  963  1485  2007
 1476  2268  3060

In [242]:
A*2

3×3 Matrix{Int64}:
  0   4   8
  6  10  14
 12  16  20

In [245]:
(3 .* A).+2 + A.^2

3×3 Matrix{Int64}:
  2  12   30
 20  42   72
 56  90  132

In [246]:
3 .* A.+2 + A.^2

3×3 Matrix{Int64}:
  2  12   30
 20  42   72
 56  90  132

In [247]:
broadcast(x->3*x+2+x^2,A)

3×3 Matrix{Int64}:
  2  12   30
 20  42   72
 56  90  132

In [250]:
(x->3*x+2+x^2).(A)

3×3 Matrix{Int64}:
  2  12   30
 20  42   72
 56  90  132

#### Importing packages

In [259]:
import LinearAlgebra

In [260]:
LinearAlgebra.I(5)

5×5 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅  ⋅
 ⋅  ⋅  1  ⋅  ⋅
 ⋅  ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  ⋅  1

In [261]:
using LinearAlgebra

In [262]:
I

UniformScaling{Bool}
true*I

In [263]:
I(17)

17×17 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1

In [264]:
using Pkg
Pkg.add("Example")

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
   Installed Example ─ v0.5.3
    Updating `~/.julia/environments/v1.8/Project.toml`
  [7876af07] + Example v0.5.3
    Updating `~/.julia/environments/v1.8/Manifest.toml`
  [7876af07] + Example v0.5.3
Precompiling project...
  ✓ Example
  1 dependency successfully precompiled in 1 seconds. 16 already precompiled.


In [265]:
using Example

In [266]:
Example.hello("Julia")

"Hello, Julia"

In [277]:
using PyCall

LoadError: ArgumentError: Package PyCall not found in current path.
- Run `import Pkg; Pkg.add("PyCall")` to install the PyCall package.

In [278]:
math = pyimport("math")

LoadError: UndefVarError: pyimport not defined

In [279]:
math.sin

LoadError: UndefVarError: math not defined

In [280]:
math.pi

LoadError: UndefVarError: math not defined

In [282]:
#np = pyimport("numpy")

In [284]:
#ENV set python path